/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MechanicRouteImport } from './routes/mechanic'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminBookingsRouteImport } from './routes/_admin.bookings'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as AdminMechanicsRouteImport } from './routes/_admin.mechanics'
import { Route as AdminNotificationsRouteImport } from './routes/_admin.notifications'
import { Route as AdminOffersRouteImport } from './routes/_admin.offers'
import { Route as AdminReportsRouteImport } from './routes/_admin.reports'
import { Route as AdminReviewsRouteImport } from './routes/_admin.reviews'
import { Route as AdminSettingsRouteImport } from './routes/_admin.settings'
import { Route as AdminUsersRouteImport } from './routes/_admin.users'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppBookingsRouteImport } from './routes/app.bookings'
import { Route as AppFavoritesRouteImport } from './routes/app.favorites'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppVehiclesRouteImport } from './routes/app.vehicles'
import { Route as MechanicIndexRouteImport } from './routes/mechanic.index'
import { Route as MechanicJobsRouteImport } from './routes/mechanic.jobs'
import { Route as MechanicNotificationsRouteImport } from './routes/mechanic.notifications'
import { Route as MechanicProfileRouteImport } from './routes/mechanic.profile'
import { Route as MechanicReviewsRouteImport } from './routes/mechanic.reviews'
import { Route as MechanicScheduleRouteImport } from './routes/mechanic.schedule'
import { Route as MechanicServicesRouteImport } from './routes/mechanic.services'
import { Route as AppMechanicIdRouteImport } from './routes/app.mechanic.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MechanicRoute = MechanicRouteImport.update({
  id: '/mechanic',
  path: '/mechanic',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMechanicsRoute = AdminMechanicsRouteImport.update({
  id: '/mechanics',
  path: '/mechanics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOffersRoute = AdminOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppBookingsRoute = AppBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppVehiclesRoute = AppVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => AppRoute,
} as any)
const MechanicIndexRoute = MechanicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MechanicRoute,
} as any)
const MechanicJobsRoute = MechanicJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => MechanicRoute,
} as any)
const MechanicNotificationsRoute = MechanicNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MechanicRoute,
} as any)
const MechanicProfileRoute = MechanicProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MechanicRoute,
} as any)
const MechanicReviewsRoute = MechanicReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => MechanicRoute,
} as any)
const MechanicScheduleRoute = MechanicScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => MechanicRoute,
} as any)
const MechanicServicesRoute = MechanicServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => MechanicRoute,
} as any)
const AppMechanicIdRoute = AppMechanicIdRouteImport.update({
  id: '/mechanic/$id',
  path: '/mechanic/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mechanic': typeof MechanicRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bookings': typeof AdminBookingsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/mechanics': typeof AdminMechanicsRoute
  '/notifications': typeof AdminNotificationsRoute
  '/offers': typeof AdminOffersRoute
  '/reports': typeof AdminReportsRoute
  '/reviews': typeof AdminReviewsRoute
  '/settings': typeof AdminSettingsRoute
  '/users': typeof AdminUsersRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/vehicles': typeof AppVehiclesRoute
  '/mechanic/jobs': typeof MechanicJobsRoute
  '/mechanic/notifications': typeof MechanicNotificationsRoute
  '/mechanic/profile': typeof MechanicProfileRoute
  '/mechanic/reviews': typeof MechanicReviewsRoute
  '/mechanic/schedule': typeof MechanicScheduleRoute
  '/mechanic/services': typeof MechanicServicesRoute
  '/app/': typeof AppIndexRoute
  '/mechanic/': typeof MechanicIndexRoute
  '/app/mechanic/$id': typeof AppMechanicIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/bookings': typeof AdminBookingsRoute
  '/dashboard': typeof AdminDashboardRoute
  '/mechanics': typeof AdminMechanicsRoute
  '/notifications': typeof AdminNotificationsRoute
  '/offers': typeof AdminOffersRoute
  '/reports': typeof AdminReportsRoute
  '/reviews': typeof AdminReviewsRoute
  '/settings': typeof AdminSettingsRoute
  '/users': typeof AdminUsersRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/vehicles': typeof AppVehiclesRoute
  '/mechanic/jobs': typeof MechanicJobsRoute
  '/mechanic/notifications': typeof MechanicNotificationsRoute
  '/mechanic/profile': typeof MechanicProfileRoute
  '/mechanic/reviews': typeof MechanicReviewsRoute
  '/mechanic/schedule': typeof MechanicScheduleRoute
  '/mechanic/services': typeof MechanicServicesRoute
  '/app': typeof AppIndexRoute
  '/mechanic': typeof MechanicIndexRoute
  '/app/mechanic/$id': typeof AppMechanicIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mechanic': typeof MechanicRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_admin/bookings': typeof AdminBookingsRoute
  '/_admin/dashboard': typeof AdminDashboardRoute
  '/_admin/mechanics': typeof AdminMechanicsRoute
  '/_admin/notifications': typeof AdminNotificationsRoute
  '/_admin/offers': typeof AdminOffersRoute
  '/_admin/reports': typeof AdminReportsRoute
  '/_admin/reviews': typeof AdminReviewsRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/users': typeof AdminUsersRoute
  '/app/bookings': typeof AppBookingsRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/vehicles': typeof AppVehiclesRoute
  '/mechanic/jobs': typeof MechanicJobsRoute
  '/mechanic/notifications': typeof MechanicNotificationsRoute
  '/mechanic/profile': typeof MechanicProfileRoute
  '/mechanic/reviews': typeof MechanicReviewsRoute
  '/mechanic/schedule': typeof MechanicScheduleRoute
  '/mechanic/services': typeof MechanicServicesRoute
  '/app/': typeof AppIndexRoute
  '/mechanic/': typeof MechanicIndexRoute
  '/app/mechanic/$id': typeof AppMechanicIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/mechanic'
    | '/privacy'
    | '/register'
    | '/sitemap.xml'
    | '/bookings'
    | '/dashboard'
    | '/mechanics'
    | '/notifications'
    | '/offers'
    | '/reports'
    | '/reviews'
    | '/settings'
    | '/users'
    | '/app/bookings'
    | '/app/favorites'
    | '/app/notifications'
    | '/app/profile'
    | '/app/search'
    | '/app/vehicles'
    | '/mechanic/jobs'
    | '/mechanic/notifications'
    | '/mechanic/profile'
    | '/mechanic/reviews'
    | '/mechanic/schedule'
    | '/mechanic/services'
    | '/app/'
    | '/mechanic/'
    | '/app/mechanic/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/privacy'
    | '/register'
    | '/sitemap.xml'
    | '/bookings'
    | '/dashboard'
    | '/mechanics'
    | '/notifications'
    | '/offers'
    | '/reports'
    | '/reviews'
    | '/settings'
    | '/users'
    | '/app/bookings'
    | '/app/favorites'
    | '/app/notifications'
    | '/app/profile'
    | '/app/search'
    | '/app/vehicles'
    | '/mechanic/jobs'
    | '/mechanic/notifications'
    | '/mechanic/profile'
    | '/mechanic/reviews'
    | '/mechanic/schedule'
    | '/mechanic/services'
    | '/app'
    | '/mechanic'
    | '/app/mechanic/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/mechanic'
    | '/privacy'
    | '/register'
    | '/sitemap.xml'
    | '/_admin/bookings'
    | '/_admin/dashboard'
    | '/_admin/mechanics'
    | '/_admin/notifications'
    | '/_admin/offers'
    | '/_admin/reports'
    | '/_admin/reviews'
    | '/_admin/settings'
    | '/_admin/users'
    | '/app/bookings'
    | '/app/favorites'
    | '/app/notifications'
    | '/app/profile'
    | '/app/search'
    | '/app/vehicles'
    | '/mechanic/jobs'
    | '/mechanic/notifications'
    | '/mechanic/profile'
    | '/mechanic/reviews'
    | '/mechanic/schedule'
    | '/mechanic/services'
    | '/app/'
    | '/mechanic/'
    | '/app/mechanic/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MechanicRoute: typeof MechanicRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mechanic': {
      id: '/mechanic'
      path: '/mechanic'
      fullPath: '/mechanic'
      preLoaderRoute: typeof MechanicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/bookings': {
      id: '/_admin/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/mechanics': {
      id: '/_admin/mechanics'
      path: '/mechanics'
      fullPath: '/mechanics'
      preLoaderRoute: typeof AdminMechanicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/notifications': {
      id: '/_admin/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/offers': {
      id: '/_admin/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AdminOffersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reports': {
      id: '/_admin/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reviews': {
      id: '/_admin/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bookings': {
      id: '/app/bookings'
      path: '/bookings'
      fullPath: '/app/bookings'
      preLoaderRoute: typeof AppBookingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/favorites': {
      id: '/app/favorites'
      path: '/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/search': {
      id: '/app/search'
      path: '/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vehicles': {
      id: '/app/vehicles'
      path: '/vehicles'
      fullPath: '/app/vehicles'
      preLoaderRoute: typeof AppVehiclesRouteImport
      parentRoute: typeof AppRoute
    }
    '/mechanic/': {
      id: '/mechanic/'
      path: '/'
      fullPath: '/mechanic/'
      preLoaderRoute: typeof MechanicIndexRouteImport
      parentRoute: typeof MechanicRoute
    }
    '/mechanic/jobs': {
      id: '/mechanic/jobs'
      path: '/jobs'
      fullPath: '/mechanic/jobs'
      preLoaderRoute: typeof MechanicJobsRouteImport
      parentRoute: typeof MechanicRoute
    }
    '/mechanic/notifications': {
      id: '/mechanic/notifications'
      path: '/notifications'
      fullPath: '/mechanic/notifications'
      preLoaderRoute: typeof MechanicNotificationsRouteImport
      parentRoute: typeof MechanicRoute
    }
    '/mechanic/profile': {
      id: '/mechanic/profile'
      path: '/profile'
      fullPath: '/mechanic/profile'
      preLoaderRoute: typeof MechanicProfileRouteImport
      parentRoute: typeof MechanicRoute
    }
    '/mechanic/reviews': {
      id: '/mechanic/reviews'
      path: '/reviews'
      fullPath: '/mechanic/reviews'
      preLoaderRoute: typeof MechanicReviewsRouteImport
      parentRoute: typeof MechanicRoute
    }
    '/mechanic/schedule': {
      id: '/mechanic/schedule'
      path: '/schedule'
      fullPath: '/mechanic/schedule'
      preLoaderRoute: typeof MechanicScheduleRouteImport
      parentRoute: typeof MechanicRoute
    }
    '/mechanic/services': {
      id: '/mechanic/services'
      path: '/services'
      fullPath: '/mechanic/services'
      preLoaderRoute: typeof MechanicServicesRouteImport
      parentRoute: typeof MechanicRoute
    }
    '/app/mechanic/$id': {
      id: '/app/mechanic/$id'
      path: '/mechanic/$id'
      fullPath: '/app/mechanic/$id'
      preLoaderRoute: typeof AppMechanicIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminMechanicsRoute: typeof AdminMechanicsRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOffersRoute: typeof AdminOffersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminMechanicsRoute: AdminMechanicsRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOffersRoute: AdminOffersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AppRouteChildren {
  AppBookingsRoute: typeof AppBookingsRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSearchRoute: typeof AppSearchRoute
  AppVehiclesRoute: typeof AppVehiclesRoute
  AppIndexRoute: typeof AppIndexRoute
  AppMechanicIdRoute: typeof AppMechanicIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBookingsRoute: AppBookingsRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppSearchRoute: AppSearchRoute,
  AppVehiclesRoute: AppVehiclesRoute,
  AppIndexRoute: AppIndexRoute,
  AppMechanicIdRoute: AppMechanicIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface MechanicRouteChildren {
  MechanicJobsRoute: typeof MechanicJobsRoute
  MechanicNotificationsRoute: typeof MechanicNotificationsRoute
  MechanicProfileRoute: typeof MechanicProfileRoute
  MechanicReviewsRoute: typeof MechanicReviewsRoute
  MechanicScheduleRoute: typeof MechanicScheduleRoute
  MechanicServicesRoute: typeof MechanicServicesRoute
  MechanicIndexRoute: typeof MechanicIndexRoute
}

const MechanicRouteChildren: MechanicRouteChildren = {
  MechanicJobsRoute: MechanicJobsRoute,
  MechanicNotificationsRoute: MechanicNotificationsRoute,
  MechanicProfileRoute: MechanicProfileRoute,
  MechanicReviewsRoute: MechanicReviewsRoute,
  MechanicScheduleRoute: MechanicScheduleRoute,
  MechanicServicesRoute: MechanicServicesRoute,
  MechanicIndexRoute: MechanicIndexRoute,
}

const MechanicRouteWithChildren = MechanicRoute._addFileChildren(
  MechanicRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MechanicRoute: MechanicRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
